### ISSUE TITLE
Adding support for molten-nvim

### ISSUE THREAD

**Issue by Maegori** [GCBallesteros/NotebookNavigator.nvim#20]
I am really enjoying using this plugin together with [molten-nvim](https://github.com/benlubas/molten-nvim) to access my REPLs, however, integrating it into the current system as set up in repls.lua turns out to be a problem. Molten does not have an init.lua, which means it can't be directly imported to pass the check in repls.lua.

To remedy this, I've opened a PR [over there](https://github.com/benlubas/molten-nvim/pull/20) which simply adds an empty init.lua to solve the issue, however, their maintainer points out that instead of creating a redundant init.lua we could import their existing health.lua. I can respect why they would rather not add a pointless file to their plugin, but it would mean that on this side we have to set the repl_provider as "molten.health". But that just looks weird and breaks with how the rest of repls.lua is set up.

So now I'm stuck, and I can't think of an elegant way to solve this problem while respecting the wishes of both molten and NotebookNavigator. My question is if you have any idea on how to solve this problem in the current framework?

Alternatively, in addition to "auto" or a REPL provider as value to repl_provider, we could add "custom" alongside a variable to which we pass a function that acts the same as the other REPL options in repls.lua. This would bypass my problem and allow users more freedom on what happens to the code before it is sent to the REPL. I would be willing to work on that.

**Comment by GCBallesteros** [comment]
Importing `molten.health` is fine. In fact for iron does not have an `init.lua` file either and we are checking for `iron.core` [here](https://github.com/GCBallesteros/NotebookNavigator.nvim/blob/51de12c70d4bddea314b017977c9d69f5f953270/lua/notebook-navigator/init.lua#L35). If you want to work on a PR I will be happy to review it, help and merge once it's ready.

**Comment by benlubas** [comment]
@Maegori I'm adding similar support for Quarto-nvim in a PR [here](https://github.com/quarto-dev/quarto-nvim/pull/99/files#diff-1919d08188aeccc1282e68ecc24ac5a27fa7b37ef2c6fb4c07b3b9c49e56bc14R81-R85). It's still a WIP, and the code is messy, but I've linked the part where I'm actually interfacing with molten to run the code. Hopefully it will help out a bit. 

I use `vim.fn.MoltenEvaluateRange(startRow, endRow, startCol, endCol)` where all of those values use 1 based indexing, and the bounds are inclusive. If you don't pass the columns, then it will run the entire line.

**Comment by TillerBurr** [comment]
I tried tackling this a bit today. I am definitely not great at lua, but I understand essentially what to do. It appears that iron.nvim does have an init.lua file (https://github.com/Vigemus/iron.nvim/blob/master/lua/iron/init.lua). I think the issue lies in here:
https://github.com/GCBallesteros/NotebookNavigator.nvim/blob/f1a0afd1d687f5fb7a07ec7997b075dc76cbee9a/lua/notebook-navigator/repls.lua#L49

Since both iron and toggleterm are directly requireable, it works out, but with molten, you cannot do a `pcall(require,'molten')`, it would have to be `pcall(require,'molten.health')`. I'm not familiar enough with lua to know the solution, but I would think a dictionary/hash table would work with the `name:import_name` and then if the `repl_provider` is 'molten', try the require on 'molten.health' and return the molten repl.

What do you think?

**Comment by benlubas** [comment]
that is the way I would do it. something like:
```lua
local names = {
	molten = "molten.health",
}
local req = names[configured_runner]
if req == nil then
	req = configured_runner
end

-- and then require(req) and go from there.
```

This way it will fallback to the config value. But honestly, there are only three code runner it's not the end of the world to just list them all out.

**Comment by GCBallesteros** [comment]
@TillerBurr you are absolutely right. I pushed a commit that adds a variable to the `utils` module, `utils.available_repls`. It is generated by the `find_supported_repls` local function in the utils module. It essentially does what @benlubas  suggests above but does it for all the providers so that the code is more uniform. Right now it's kind of trivial but provides the extra flexibility required to fix the situation.

This also makes it possible to get rid of the code at the beginning of the `init.lua` that checks (again) for the repls. Will do that as soon as I have some bandwidth.
