### ISSUE TITLE
set up Notebook Navigator only if buffer is notebook

### ISSUE THREAD

**Issue by dlyongemallo** [GCBallesteros/NotebookNavigator.nvim#55]
This is possibly a configuration issue on my end, but I have Notebook Navigator set up with Jupytext with standard/default settings and it works great. 

The problem is that I sometimes accidentally hit a shortcut key, e.g., `<leader>x` for `run_and_move`, while editing a regular (i.e., non-notebook) Python file, and this results in a long error message (`Failed to load python3 host...`) which effectively just says that I can't run Notebook Navigator because there are no cells. This happens for some files but not others (which are treated as if the entire file were one giant cell), but I'm not sure what the difference between them is. In any case, I don't want Notebook Navigator to try to run non-notebook files.

I tried using `ftplugin` to selectively enable/disable Notebook Navigator, but both Python files (`*.py`) and Jupyter notebook files (`*.ipynb`) seem to have a `filetype` of `python` in my configuration. (I think this is because of jupytext.nvim, as otherwise `*.ipynb` files are detected as `json`.) Is there a way to detect whether the buffer is a regular Python file vs. a notebook, or set up Notebook Navigator only for notebooks? Or otherwise set things up in a way that the shortcut key is not mapped (or is ignored) when not in a notebook, or to make it so the error message is nicer?

**Comment by GCBallesteros** [comment]
Indeed, the filetype being python is jupytext's doing. This is needed so that things like LSP and syntax highlighting work. Notebook navigator doesn't know a thing about jupytext.nvim and viceversa. From the point of view of NotebookNavigator any buffer may be a valid notebook. Not sure about how to go about it without coupling NotebookNavigator to jupytext but I'm open to ideas on how to disable the keymaps when not working with jupytext.

edit: A light coupling of the two would be fine. For example jupytext could register what buffers it has created and Notebook Navigator could check for those and optionally disable itself if not on a jupytext modified buffer.

**Comment by dlyongemallo** [comment]
Okay, I did the obvious (perhaps inelegant) thing and added logic to detect the file extension in `$HOME/.config/nvim/after/ftplugin/python.lua`:

```lua
local extension = vim.fn.expand('%:e')
if string.lower(extension) == "ipynb" then
    local nn = require("notebook-navigator")
    nn.setup({
        ...
    })
    ...
end
```

Of course, this depends on files being Jupyter Notebooks if and only if they have the extension "ipynb", but I can't think of why that assumption would ever be violated. 

In fact, adding this gating logic has the additional benefit that if I accidentally opened the `.py` file associated by jupytext with a `.ipynb` file (instead of the `.ipynb` itself), Notebook Navigator isn't loaded. This alerts me that I should open the `.ipynb` directly instead, so that I don't edit the `.py` file and put things out of sync.

This solves my problem. It might be worthwhile to document the above in case it's useful to anyone else.

**Comment by GCBallesteros** [comment]
Glad you were able to fix that. Good luck on your endeavors!
